# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20181210_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True),
        ),
    ]
